### ISSUE TITLE
DEV version: Own goals is counted for the wrong team

### ISSUE THREAD

**Issue by piratenfuerimmer** [bigpapy/htlivesight#25]
Today I re-watched my youth team's win in htlivesight DEV (Aug 2020 version), and the other team scored an own goal. htlivesight incorrectly counted the goal for the other team. Screenshot attached. Thank you for an awesome re-live viewer!
![Screenshot from 2020-12-14 10-37-09](https://user-images.githubusercontent.com/68741966/102027964-cd934b00-3dfb-11eb-9ed3-0187beb6fc87.png)

**Comment by bigpapy** [comment]
@piratenfuerimmer Thank you for your report. Can you write me the match id?

**Comment by piratenfuerimmer** [comment]
No worries: 116343633


----- Original message -----

**Comment by bigpapy** [comment]
It should be fixed in next dev version. Hoping to release it in first days of the new year.

**Comment by piratenfuerimmer** [comment]
Thanks mate, well done!

Stefan🤶🙂


----- Original message -----
